#include "Render.h"
#include "Mem.h"
#include "Types.h"

RenderBuf RenderBufInit(MemAlloc *MemAlloc, Uint32 Cap)
{
    RenderBuf Result = {};

    Assert(MemAlloc);
    Assert(Cap > 0);

    Result.Mem = (Uint8 *)MemAllocPush(MemAlloc, Cap);
    if (Result.Mem)
    {
        Result.Size = 0;
        Result.Cap = Cap;
        Result.IsValid = True;

        return Result;
    }

    return Result;
}

Void *RenderBufPush(RenderBuf *RenderBuf, Uint32 Bytes)
{
    Assert(RenderBuf);
    Assert(Bytes >= sizeof(RenderHeader)); // NOTE: Always must be room for the header.

    Uint32 Aligned = BufAlignUp(Bytes);

    Bool HasSpace = (RenderBuf->Size + Aligned) <= RenderBuf->Cap;
    Assert(HasSpace);

    if (HasSpace)
    {
        Uint32 Offset = BufAlignUp(RenderBuf->Size);
        Void *Result = RenderBuf->Mem + Offset;
        RenderBuf->Size = Offset + Aligned;

        return Result;
    }

    return 0;
}

Void RenderBufClear(RenderBuf *RenderBuf, Color Color)
{
    RenderClear *Cmd = (RenderClear *)RenderBufPush(RenderBuf, sizeof(RenderClear));

    if (Cmd)
    {
        Cmd->Header.Type = RenderCommand_Clear;
        Cmd->Header.Size = BufAlignUp(sizeof(RenderClear));

        Cmd->Color = Color;
    }
}

Void RenderBufDrawDebugText(RenderBuf *RenderBuf, Color Color, V2 Pos, V2 Scale, const char *Str, Uint32 StrLen)
{
    if (!Str || StrLen == 0)
    {
        return;
    }

    Uint32 StrCap = StrLen + 1;
    Uint32 Size = sizeof(RenderDrawDebugText) + StrCap;
    RenderDrawDebugText *Cmd = (RenderDrawDebugText *)RenderBufPush(RenderBuf, Size);

    if (Cmd)
    {
        Cmd->Header.Type = RenderCommand_DrawDebugText;
        Cmd->Header.Size = BufAlignUp(Size);

        Cmd->Pos = Pos;
        Cmd->Color = Color;
        Cmd->Scale = Scale;

        MemCopy(Cmd->Str, Str, StrLen);
        MemNullTerminate(Cmd->Str, StrCap, StrLen);
    }
}

Void RenderBufDrawCStr(RenderBuf *RenderBuf, Color Color, V2 Pos, V2 Scale, const char *Str)
{
    RenderBufDrawDebugText(RenderBuf, Color, Pos, Scale, Str, CStrLen(Str));
}

Void RenderBufDrawRect(RenderBuf *RenderBuf, TexHandle Tex, Rect Dst, Rect Src, Color Color)
{
    RenderDrawRect *Cmd = (RenderDrawRect *)RenderBufPush(RenderBuf, sizeof(RenderDrawRect));

    if (Cmd)
    {
        Cmd->Header.Type = RenderCommand_DrawRect;
        Cmd->Header.Size = BufAlignUp(sizeof(RenderDrawRect));

        Cmd->Tex = Tex;
        Cmd->Dst = Dst;
        Cmd->Src = Src;
        Cmd->Color = Color;
    }
}

Void RenderBufReset(RenderBuf *RenderBuf)
{
    RenderBuf->Size = 0;
}

//
// NOTE: Atlas utilities.
//

// NOTE: Meta is expected to use the same format generated by AtlasPack:
//
// <image_path> <x_position> <y_position> <width> <height>

Atlas AtlasInit(MemAlloc *Alloc, TexHandle Tex, const char *Meta, Uint32 MetaLen)
{
    Atlas Result = {0};
    Assert(Alloc);

    if (!Meta || MetaLen == 0)
    {
        return Result;
    }

    Result.Tex = Tex;

    Uint32 LineCount = 0;
    const char *LineScan = Meta;
    const char *MetaEnd = Meta + MetaLen;
    while (LineScan < MetaEnd)
    {
        LineCount++;
        const char *NextLine = MemFindChar(LineScan, MetaEnd, '\n');

        if (!NextLine)
        {
            break;
        }

        LineScan = NextLine + 1;
    }

    if (LineCount == 0)
    {
        return Result;
    }

    Result.Entries = (AtlasEntry *)MemAllocPush(Alloc, sizeof(AtlasEntry) * LineCount);
    if (!Result.Entries)
    {
        return Result;
    }
    Result.Cap = LineCount;

    const char *Cur = Meta;
    const char *End = Meta + MetaLen;

    while (Cur < End && Result.Count < Result.Cap)
    {
        const char *LineEnd = MemFindChar(Cur, End, '\n');
        if (!LineEnd)
        {
            LineEnd = End;
        }

        const char *Space = MemFindChar(Cur, LineEnd, ' ');
        if (!Space)
        {
            MemAdvanceToNextLine(&Cur, End);
            continue;
        }

        Uint32 PathLen = (Uint32)(Space - Cur);
        const char *BaseName = GetBaseName(Cur, PathLen);
        Uint32 BaseLen = (Uint32)(Space - BaseName);

        AtlasEntry *Entry = &Result.Entries[Result.Count++];

        Uint32 CopyLen = BaseLen < (ATLAS_MAX_NAME - 1) ? BaseLen : (ATLAS_MAX_NAME - 1);
        MemCopy(Entry->Name, BaseName, CopyLen);
        MemNullTerminate(Entry->Name, ATLAS_MAX_NAME, CopyLen);

        Cur = Space;

        Entry->Src.Pos.X = (Float32)MemParseUint(&Cur);
        Entry->Src.Pos.Y = (Float32)MemParseUint(&Cur);
        Entry->Src.Size.W = (Float32)MemParseUint(&Cur);
        Entry->Src.Size.H = (Float32)MemParseUint(&Cur);

        MemAdvanceToNextLine(&Cur, End);
    }

    Result.IsValid = True;
    return Result;
}

Rect AtlasGetRect(Atlas *Atlas, const char *Name)
{
    Rect Result = {0};

    Assert(Atlas);
    Assert(Name);

    if (!Atlas->IsValid)
    {
        return Result;
    }

    Uint32 NameLen = CStrLen(Name);
    for (Uint32 I = 0; I < Atlas->Count; ++I)
    {
        AtlasEntry *Entry = &Atlas->Entries[I];

        Bool Match = True;
        for (Uint32 C = 0; C <= NameLen; ++C)
        {
            if (Entry->Name[C] != Name[C])
            {
                Match = False;
                break;
            }
        }

        if (Match)
        {
            return Entry->Src;
        }
    }

    return Result;
}
