#if !defined(RENDER_H)
#define RENDER_H

#include "Math.h"
#include "Mem.h"
#include "Types.h"

#define BufAlign 4
StaticAssert(IsPow2(BufAlign));

#define BufAlignUp(Value) AlignUp(Value, BufAlign)

#define InternalRes V2Make(1280.0f, 720.0f)
#define ScreenCenter V2Unscale(InternalRes, 2.0f)

// NOTE:
// 1. All positions are in pixels, with origin for everyone being the top-left.
// 2. Intenally renderer uses letterboxing with the resolution of 1280x720

typedef Uint32 TexHandle;
#define TexHandleInvalid 0xFFFFFFFF

typedef enum
{
    RenderCommand_None,
    RenderCommand_Clear,
    RenderCommand_DrawDebugText,
    RenderCommand_DrawRect,
} RenderCommand;

// NOTE: Every command must start with this header for iterators sake.
typedef struct
{
    RenderCommand Type;
    // NOTE: Must store aligned size here!!!
    Uint32 Size;
} RenderHeader;

// NOTE: Clears the entire screen with the specified `Color`.
typedef struct
{
    RenderHeader Header;

    Color Color;
} RenderClear;

// NOTE: Character size for the debug font.
#define DebugTextCharSize 8
// NOTE: There's a reason why this command is called 'draw DEBUG' text and
// that reason is that the implementation of it just uses SDL built-in
// SDL_RenderDebugText function, which provides just simple bitmap
// font rendering intended for, as you probably already guessed,
// debugging.
typedef struct
{
    RenderHeader Header;

    V2 Pos;
    Color Color;
    // NOTE: Scale multiplier.
    V2 Scale;

    Uint32 StrLen;
    // NOTE: The final newline is not appended!
    char Str[];
} RenderDrawDebugText;

typedef struct
{
    RenderHeader Header;

    // NOTE: This can be TexHandleInvalid for a regular untextured rectangle.
    TexHandle Tex;

    // NOTE: Where on screen to draw the rectangle.
    Rect Dst;
    // NOTE: Which part of the texture draw. If Src.Pos is 0,0, then the entire
    // image is drawn.
    // This is fully ignored if Tex is TexHandleInvalid.
    Rect Src;

    // NOTE: If Tex is TexHandleInvalid then it's the color of the rectangle.
    // Otherwise acts as a tint. For unmodified keep it as White.
    Color Color;
} RenderDrawRect;

typedef struct
{
    Uint8 *Mem;
    Uint32 Size;
    Uint32 Cap;

    Bool IsValid;
} RenderBuf;

RenderBuf RenderBufInit(MemAlloc *MemAlloc, Uint32 Cap);

Void *RenderBufPush(RenderBuf *RenderBuf, Uint32 Bytes);
Void RenderBufClear(RenderBuf *RenderBuf, Color Color);
Void RenderBufDrawDebugText(RenderBuf *RenderBuf, Color Color, V2 Pos, V2 Scale, const char *Str, Uint32 StrLen);
Void RenderBufDrawCStr(RenderBuf *RenderBuf, Color Color, V2 Pos, V2 Scale, const char *Str);
// NOTE: If you're thinking 'It is too inconvinient to pass Dst and Src
// everytime!' then you're probably doing something wrong. Standard untextured
// rectangles shouldn't be a thing you do very often and if you're actually
// using spritesheets like intended it should not seem as inconvinient.
Void RenderBufDrawRect(RenderBuf *RenderBuf, TexHandle Tex, Rect Dst, Rect Src, Color Color);

Void RenderBufReset(RenderBuf *RenderBuf);
// NOTE: This is used only internally.
#define RenderBufIterate(BufPtr, CmdPtrName)                       \
    for (RenderHeader *CmdPtrName = (RenderHeader *)(BufPtr)->Mem; \
         (Uint8 *)CmdPtrName < (BufPtr)->Mem + (BufPtr)->Size;     \
         CmdPtrName = (RenderHeader *)((Uint8 *)CmdPtrName + CmdPtrName->Size))

//
// NOTE: Atlas utilities.
//

#define ATLAS_MAX_NAME 64

typedef struct
{
    char Name[ATLAS_MAX_NAME];
    Rect Src;
} AtlasEntry;

typedef struct
{
    TexHandle Tex;

    AtlasEntry *Entries;
    Uint32 Count;
    Uint32 Cap;

    Bool IsValid;
} Atlas;

// NOTE: Meta is expected to use the same format generated by AtlasPack:
//
// <image_path> <x_position> <y_position> <width> <height>
Atlas AtlasInit(MemAlloc *Alloc, TexHandle Tex, const char *Meta, Uint32 MetaLen);

Rect AtlasGetRect(Atlas *Atlas, const char *Name);

#endif
